// Package tmdb provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package tmdb

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	Sec0Scopes = "sec0.Scopes"
)

// Defines values for AccountGetFavoritesParamsSortBy.
const (
	AccountGetFavoritesParamsSortByCreatedAtAsc  AccountGetFavoritesParamsSortBy = "created_at.asc"
	AccountGetFavoritesParamsSortByCreatedAtDesc AccountGetFavoritesParamsSortBy = "created_at.desc"
)

// Defines values for AccountFavoriteTvParamsSortBy.
const (
	AccountFavoriteTvParamsSortByCreatedAtAsc  AccountFavoriteTvParamsSortBy = "created_at.asc"
	AccountFavoriteTvParamsSortByCreatedAtDesc AccountFavoriteTvParamsSortBy = "created_at.desc"
)

// Defines values for AccountRatedMoviesParamsSortBy.
const (
	AccountRatedMoviesParamsSortByCreatedAtAsc  AccountRatedMoviesParamsSortBy = "created_at.asc"
	AccountRatedMoviesParamsSortByCreatedAtDesc AccountRatedMoviesParamsSortBy = "created_at.desc"
)

// Defines values for AccountRatedTvParamsSortBy.
const (
	AccountRatedTvParamsSortByCreatedAtAsc  AccountRatedTvParamsSortBy = "created_at.asc"
	AccountRatedTvParamsSortByCreatedAtDesc AccountRatedTvParamsSortBy = "created_at.desc"
)

// Defines values for AccountRatedTvEpisodesParamsSortBy.
const (
	AccountRatedTvEpisodesParamsSortByCreatedAtAsc  AccountRatedTvEpisodesParamsSortBy = "created_at.asc"
	AccountRatedTvEpisodesParamsSortByCreatedAtDesc AccountRatedTvEpisodesParamsSortBy = "created_at.desc"
)

// Defines values for AccountWatchlistMoviesParamsSortBy.
const (
	AccountWatchlistMoviesParamsSortByCreatedAtAsc  AccountWatchlistMoviesParamsSortBy = "created_at.asc"
	AccountWatchlistMoviesParamsSortByCreatedAtDesc AccountWatchlistMoviesParamsSortBy = "created_at.desc"
)

// Defines values for AccountWatchlistTvParamsSortBy.
const (
	AccountWatchlistTvParamsSortByCreatedAtAsc  AccountWatchlistTvParamsSortBy = "created_at.asc"
	AccountWatchlistTvParamsSortByCreatedAtDesc AccountWatchlistTvParamsSortBy = "created_at.desc"
)

// Defines values for DiscoverMovieParamsSortBy.
const (
	DiscoverMovieParamsSortByOriginalTitleAsc       DiscoverMovieParamsSortBy = "original_title.asc"
	DiscoverMovieParamsSortByOriginalTitleDesc      DiscoverMovieParamsSortBy = "original_title.desc"
	DiscoverMovieParamsSortByPopularityAsc          DiscoverMovieParamsSortBy = "popularity.asc"
	DiscoverMovieParamsSortByPopularityDesc         DiscoverMovieParamsSortBy = "popularity.desc"
	DiscoverMovieParamsSortByPrimaryReleaseDateAsc  DiscoverMovieParamsSortBy = "primary_release_date.asc"
	DiscoverMovieParamsSortByPrimaryReleaseDateDesc DiscoverMovieParamsSortBy = "primary_release_date.desc"
	DiscoverMovieParamsSortByRevenueAsc             DiscoverMovieParamsSortBy = "revenue.asc"
	DiscoverMovieParamsSortByRevenueDesc            DiscoverMovieParamsSortBy = "revenue.desc"
	DiscoverMovieParamsSortByTitleAsc               DiscoverMovieParamsSortBy = "title.asc"
	DiscoverMovieParamsSortByTitleDesc              DiscoverMovieParamsSortBy = "title.desc"
	DiscoverMovieParamsSortByVoteAverageAsc         DiscoverMovieParamsSortBy = "vote_average.asc"
	DiscoverMovieParamsSortByVoteAverageDesc        DiscoverMovieParamsSortBy = "vote_average.desc"
	DiscoverMovieParamsSortByVoteCountAsc           DiscoverMovieParamsSortBy = "vote_count.asc"
	DiscoverMovieParamsSortByVoteCountDesc          DiscoverMovieParamsSortBy = "vote_count.desc"
)

// Defines values for DiscoverTvParamsSortBy.
const (
	DiscoverTvParamsSortByFirstAirDateAsc  DiscoverTvParamsSortBy = "first_air_date.asc"
	DiscoverTvParamsSortByFirstAirDateDesc DiscoverTvParamsSortBy = "first_air_date.desc"
	DiscoverTvParamsSortByNameAsc          DiscoverTvParamsSortBy = "name.asc"
	DiscoverTvParamsSortByNameDesc         DiscoverTvParamsSortBy = "name.desc"
	DiscoverTvParamsSortByOriginalNameAsc  DiscoverTvParamsSortBy = "original_name.asc"
	DiscoverTvParamsSortByOriginalNameDesc DiscoverTvParamsSortBy = "original_name.desc"
	DiscoverTvParamsSortByPopularityAsc    DiscoverTvParamsSortBy = "popularity.asc"
	DiscoverTvParamsSortByPopularityDesc   DiscoverTvParamsSortBy = "popularity.desc"
	DiscoverTvParamsSortByVoteAverageAsc   DiscoverTvParamsSortBy = "vote_average.asc"
	DiscoverTvParamsSortByVoteAverageDesc  DiscoverTvParamsSortBy = "vote_average.desc"
	DiscoverTvParamsSortByVoteCountAsc     DiscoverTvParamsSortBy = "vote_count.asc"
	DiscoverTvParamsSortByVoteCountDesc    DiscoverTvParamsSortBy = "vote_count.desc"
)

// Defines values for FindByIdParamsExternalSource.
const (
	Empty       FindByIdParamsExternalSource = ""
	FacebookId  FindByIdParamsExternalSource = "facebook_id"
	ImdbId      FindByIdParamsExternalSource = "imdb_id"
	InstagramId FindByIdParamsExternalSource = "instagram_id"
	TiktokId    FindByIdParamsExternalSource = "tiktok_id"
	TvdbId      FindByIdParamsExternalSource = "tvdb_id"
	TwitterId   FindByIdParamsExternalSource = "twitter_id"
	WikidataId  FindByIdParamsExternalSource = "wikidata_id"
	YoutubeId   FindByIdParamsExternalSource = "youtube_id"
)

// Defines values for GuestSessionRatedMoviesParamsSortBy.
const (
	GuestSessionRatedMoviesParamsSortByCreatedAtAsc  GuestSessionRatedMoviesParamsSortBy = "created_at.asc"
	GuestSessionRatedMoviesParamsSortByCreatedAtDesc GuestSessionRatedMoviesParamsSortBy = "created_at.desc"
)

// Defines values for GuestSessionRatedTvParamsSortBy.
const (
	GuestSessionRatedTvParamsSortByCreatedAtAsc  GuestSessionRatedTvParamsSortBy = "created_at.asc"
	GuestSessionRatedTvParamsSortByCreatedAtDesc GuestSessionRatedTvParamsSortBy = "created_at.desc"
)

// Defines values for GuestSessionRatedTvEpisodesParamsSortBy.
const (
	GuestSessionRatedTvEpisodesParamsSortByCreatedAtAsc  GuestSessionRatedTvEpisodesParamsSortBy = "created_at.asc"
	GuestSessionRatedTvEpisodesParamsSortByCreatedAtDesc GuestSessionRatedTvEpisodesParamsSortBy = "created_at.desc"
)

// Defines values for TrendingAllParamsTimeWindow.
const (
	TrendingAllParamsTimeWindowDay  TrendingAllParamsTimeWindow = "day"
	TrendingAllParamsTimeWindowWeek TrendingAllParamsTimeWindow = "week"
)

// Defines values for TrendingMoviesParamsTimeWindow.
const (
	TrendingMoviesParamsTimeWindowDay  TrendingMoviesParamsTimeWindow = "day"
	TrendingMoviesParamsTimeWindowWeek TrendingMoviesParamsTimeWindow = "week"
)

// Defines values for TrendingPeopleParamsTimeWindow.
const (
	TrendingPeopleParamsTimeWindowDay  TrendingPeopleParamsTimeWindow = "day"
	TrendingPeopleParamsTimeWindowWeek TrendingPeopleParamsTimeWindow = "week"
)

// Defines values for TrendingTvParamsTimeWindow.
const (
	TrendingTvParamsTimeWindowDay  TrendingTvParamsTimeWindow = "day"
	TrendingTvParamsTimeWindowWeek TrendingTvParamsTimeWindow = "week"
)

// AccountDetailsParams defines parameters for AccountDetails.
type AccountDetailsParams struct {
	SessionId *string `form:"session_id,omitempty" json:"session_id,omitempty"`
}

// AccountAddFavoriteJSONBody defines parameters for AccountAddFavorite.
type AccountAddFavoriteJSONBody struct {
	Favorite  *bool   `json:"favorite,omitempty"`
	MediaId   *int    `json:"media_id,omitempty"`
	MediaType *string `json:"media_type,omitempty"`
}

// AccountAddFavoriteParams defines parameters for AccountAddFavorite.
type AccountAddFavoriteParams struct {
	SessionId *string `form:"session_id,omitempty" json:"session_id,omitempty"`
}

// AccountGetFavoritesParams defines parameters for AccountGetFavorites.
type AccountGetFavoritesParams struct {
	Language  *string                          `form:"language,omitempty" json:"language,omitempty"`
	Page      *int32                           `form:"page,omitempty" json:"page,omitempty"`
	SessionId *string                          `form:"session_id,omitempty" json:"session_id,omitempty"`
	SortBy    *AccountGetFavoritesParamsSortBy `form:"sort_by,omitempty" json:"sort_by,omitempty"`
}

// AccountGetFavoritesParamsSortBy defines parameters for AccountGetFavorites.
type AccountGetFavoritesParamsSortBy string

// AccountFavoriteTvParams defines parameters for AccountFavoriteTv.
type AccountFavoriteTvParams struct {
	Language  *string                        `form:"language,omitempty" json:"language,omitempty"`
	Page      *int32                         `form:"page,omitempty" json:"page,omitempty"`
	SessionId *string                        `form:"session_id,omitempty" json:"session_id,omitempty"`
	SortBy    *AccountFavoriteTvParamsSortBy `form:"sort_by,omitempty" json:"sort_by,omitempty"`
}

// AccountFavoriteTvParamsSortBy defines parameters for AccountFavoriteTv.
type AccountFavoriteTvParamsSortBy string

// AccountListsParams defines parameters for AccountLists.
type AccountListsParams struct {
	Page      *int32  `form:"page,omitempty" json:"page,omitempty"`
	SessionId *string `form:"session_id,omitempty" json:"session_id,omitempty"`
}

// AccountRatedMoviesParams defines parameters for AccountRatedMovies.
type AccountRatedMoviesParams struct {
	Language  *string                         `form:"language,omitempty" json:"language,omitempty"`
	Page      *int32                          `form:"page,omitempty" json:"page,omitempty"`
	SessionId *string                         `form:"session_id,omitempty" json:"session_id,omitempty"`
	SortBy    *AccountRatedMoviesParamsSortBy `form:"sort_by,omitempty" json:"sort_by,omitempty"`
}

// AccountRatedMoviesParamsSortBy defines parameters for AccountRatedMovies.
type AccountRatedMoviesParamsSortBy string

// AccountRatedTvParams defines parameters for AccountRatedTv.
type AccountRatedTvParams struct {
	Language  *string                     `form:"language,omitempty" json:"language,omitempty"`
	Page      *int32                      `form:"page,omitempty" json:"page,omitempty"`
	SessionId *string                     `form:"session_id,omitempty" json:"session_id,omitempty"`
	SortBy    *AccountRatedTvParamsSortBy `form:"sort_by,omitempty" json:"sort_by,omitempty"`
}

// AccountRatedTvParamsSortBy defines parameters for AccountRatedTv.
type AccountRatedTvParamsSortBy string

// AccountRatedTvEpisodesParams defines parameters for AccountRatedTvEpisodes.
type AccountRatedTvEpisodesParams struct {
	Language  *string                             `form:"language,omitempty" json:"language,omitempty"`
	Page      *int32                              `form:"page,omitempty" json:"page,omitempty"`
	SessionId *string                             `form:"session_id,omitempty" json:"session_id,omitempty"`
	SortBy    *AccountRatedTvEpisodesParamsSortBy `form:"sort_by,omitempty" json:"sort_by,omitempty"`
}

// AccountRatedTvEpisodesParamsSortBy defines parameters for AccountRatedTvEpisodes.
type AccountRatedTvEpisodesParamsSortBy string

// AccountAddToWatchlistJSONBody defines parameters for AccountAddToWatchlist.
type AccountAddToWatchlistJSONBody struct {
	MediaId   *int    `json:"media_id,omitempty"`
	MediaType *string `json:"media_type,omitempty"`
	Watchlist *bool   `json:"watchlist,omitempty"`
}

// AccountAddToWatchlistParams defines parameters for AccountAddToWatchlist.
type AccountAddToWatchlistParams struct {
	SessionId *string `form:"session_id,omitempty" json:"session_id,omitempty"`
}

// AccountWatchlistMoviesParams defines parameters for AccountWatchlistMovies.
type AccountWatchlistMoviesParams struct {
	Language  *string                             `form:"language,omitempty" json:"language,omitempty"`
	Page      *int32                              `form:"page,omitempty" json:"page,omitempty"`
	SessionId *string                             `form:"session_id,omitempty" json:"session_id,omitempty"`
	SortBy    *AccountWatchlistMoviesParamsSortBy `form:"sort_by,omitempty" json:"sort_by,omitempty"`
}

// AccountWatchlistMoviesParamsSortBy defines parameters for AccountWatchlistMovies.
type AccountWatchlistMoviesParamsSortBy string

// AccountWatchlistTvParams defines parameters for AccountWatchlistTv.
type AccountWatchlistTvParams struct {
	Language  *string                         `form:"language,omitempty" json:"language,omitempty"`
	Page      *int32                          `form:"page,omitempty" json:"page,omitempty"`
	SessionId *string                         `form:"session_id,omitempty" json:"session_id,omitempty"`
	SortBy    *AccountWatchlistTvParamsSortBy `form:"sort_by,omitempty" json:"sort_by,omitempty"`
}

// AccountWatchlistTvParamsSortBy defines parameters for AccountWatchlistTv.
type AccountWatchlistTvParamsSortBy string

// AuthenticationDeleteSessionJSONBody defines parameters for AuthenticationDeleteSession.
type AuthenticationDeleteSessionJSONBody struct {
	SessionId *string `json:"session_id,omitempty"`
}

// AuthenticationCreateSessionFromV4TokenJSONBody defines parameters for AuthenticationCreateSessionFromV4Token.
type AuthenticationCreateSessionFromV4TokenJSONBody struct {
	AccessToken *string `json:"access_token,omitempty"`
}

// AuthenticationCreateSessionJSONBody defines parameters for AuthenticationCreateSession.
type AuthenticationCreateSessionJSONBody struct {
	RequestToken *string `json:"request_token,omitempty"`
}

// AuthenticationCreateSessionFromLoginJSONBody defines parameters for AuthenticationCreateSessionFromLogin.
type AuthenticationCreateSessionFromLoginJSONBody struct {
	Password     *string `json:"password,omitempty"`
	RequestToken *string `json:"request_token,omitempty"`
	Username     *string `json:"username,omitempty"`
}

// CollectionDetailsParams defines parameters for CollectionDetails.
type CollectionDetailsParams struct {
	Language *string `form:"language,omitempty" json:"language,omitempty"`
}

// CollectionImagesParams defines parameters for CollectionImages.
type CollectionImagesParams struct {
	// IncludeImageLanguage specify a comma separated list of ISO-639-1 values to query, for example: `en,null`
	IncludeImageLanguage *string `form:"include_image_language,omitempty" json:"include_image_language,omitempty"`
	Language             *string `form:"language,omitempty" json:"language,omitempty"`
}

// ConfigurationCountriesParams defines parameters for ConfigurationCountries.
type ConfigurationCountriesParams struct {
	Language *string `form:"language,omitempty" json:"language,omitempty"`
}

// DiscoverMovieParams defines parameters for DiscoverMovie.
type DiscoverMovieParams struct {
	// Certification use in conjunction with `region`
	Certification *string `form:"certification,omitempty" json:"certification,omitempty"`

	// CertificationGte use in conjunction with `region`
	CertificationGte *string `form:"certification.gte,omitempty" json:"certification.gte,omitempty"`

	// CertificationLte use in conjunction with `region`
	CertificationLte *string `form:"certification.lte,omitempty" json:"certification.lte,omitempty"`

	// CertificationCountry use in conjunction with the `certification`, `certification.gte` and `certification.lte` filters
	CertificationCountry  *string                    `form:"certification_country,omitempty" json:"certification_country,omitempty"`
	IncludeAdult          *bool                      `form:"include_adult,omitempty" json:"include_adult,omitempty"`
	IncludeVideo          *bool                      `form:"include_video,omitempty" json:"include_video,omitempty"`
	Language              *string                    `form:"language,omitempty" json:"language,omitempty"`
	Page                  *int32                     `form:"page,omitempty" json:"page,omitempty"`
	PrimaryReleaseYear    *int32                     `form:"primary_release_year,omitempty" json:"primary_release_year,omitempty"`
	PrimaryReleaseDateGte *openapi_types.Date        `form:"primary_release_date.gte,omitempty" json:"primary_release_date.gte,omitempty"`
	PrimaryReleaseDateLte *openapi_types.Date        `form:"primary_release_date.lte,omitempty" json:"primary_release_date.lte,omitempty"`
	Region                *string                    `form:"region,omitempty" json:"region,omitempty"`
	ReleaseDateGte        *openapi_types.Date        `form:"release_date.gte,omitempty" json:"release_date.gte,omitempty"`
	ReleaseDateLte        *openapi_types.Date        `form:"release_date.lte,omitempty" json:"release_date.lte,omitempty"`
	SortBy                *DiscoverMovieParamsSortBy `form:"sort_by,omitempty" json:"sort_by,omitempty"`
	VoteAverageGte        *float32                   `form:"vote_average.gte,omitempty" json:"vote_average.gte,omitempty"`
	VoteAverageLte        *float32                   `form:"vote_average.lte,omitempty" json:"vote_average.lte,omitempty"`
	VoteCountGte          *float32                   `form:"vote_count.gte,omitempty" json:"vote_count.gte,omitempty"`
	VoteCountLte          *float32                   `form:"vote_count.lte,omitempty" json:"vote_count.lte,omitempty"`

	// WatchRegion use in conjunction with `with_watch_monetization_types ` or `with_watch_providers `
	WatchRegion *string `form:"watch_region,omitempty" json:"watch_region,omitempty"`

	// WithCast can be a comma (`AND`) or pipe (`OR`) separated query
	WithCast *string `form:"with_cast,omitempty" json:"with_cast,omitempty"`

	// WithCompanies can be a comma (`AND`) or pipe (`OR`) separated query
	WithCompanies *string `form:"with_companies,omitempty" json:"with_companies,omitempty"`

	// WithCrew can be a comma (`AND`) or pipe (`OR`) separated query
	WithCrew *string `form:"with_crew,omitempty" json:"with_crew,omitempty"`

	// WithGenres can be a comma (`AND`) or pipe (`OR`) separated query
	WithGenres *string `form:"with_genres,omitempty" json:"with_genres,omitempty"`

	// WithKeywords can be a comma (`AND`) or pipe (`OR`) separated query
	WithKeywords         *string `form:"with_keywords,omitempty" json:"with_keywords,omitempty"`
	WithOriginCountry    *string `form:"with_origin_country,omitempty" json:"with_origin_country,omitempty"`
	WithOriginalLanguage *string `form:"with_original_language,omitempty" json:"with_original_language,omitempty"`

	// WithPeople can be a comma (`AND`) or pipe (`OR`) separated query
	WithPeople *string `form:"with_people,omitempty" json:"with_people,omitempty"`

	// WithReleaseType possible values are: [1, 2, 3, 4, 5, 6] can be a comma (`AND`) or pipe (`OR`) separated query, can be used in conjunction with `region`
	WithReleaseType *int32 `form:"with_release_type,omitempty" json:"with_release_type,omitempty"`
	WithRuntimeGte  *int32 `form:"with_runtime.gte,omitempty" json:"with_runtime.gte,omitempty"`
	WithRuntimeLte  *int32 `form:"with_runtime.lte,omitempty" json:"with_runtime.lte,omitempty"`

	// WithWatchMonetizationTypes possible values are: [flatrate, free, ads, rent, buy] use in conjunction with `watch_region`, can be a comma (`AND`) or pipe (`OR`) separated query
	WithWatchMonetizationTypes *string `form:"with_watch_monetization_types,omitempty" json:"with_watch_monetization_types,omitempty"`

	// WithWatchProviders use in conjunction with `watch_region`, can be a comma (`AND`) or pipe (`OR`) separated query
	WithWatchProviders    *string `form:"with_watch_providers,omitempty" json:"with_watch_providers,omitempty"`
	WithoutCompanies      *string `form:"without_companies,omitempty" json:"without_companies,omitempty"`
	WithoutGenres         *string `form:"without_genres,omitempty" json:"without_genres,omitempty"`
	WithoutKeywords       *string `form:"without_keywords,omitempty" json:"without_keywords,omitempty"`
	WithoutWatchProviders *string `form:"without_watch_providers,omitempty" json:"without_watch_providers,omitempty"`
	Year                  *int32  `form:"year,omitempty" json:"year,omitempty"`
}

// DiscoverMovieParamsSortBy defines parameters for DiscoverMovie.
type DiscoverMovieParamsSortBy string

// DiscoverTvParams defines parameters for DiscoverTv.
type DiscoverTvParams struct {
	AirDateGte               *openapi_types.Date     `form:"air_date.gte,omitempty" json:"air_date.gte,omitempty"`
	AirDateLte               *openapi_types.Date     `form:"air_date.lte,omitempty" json:"air_date.lte,omitempty"`
	FirstAirDateYear         *int32                  `form:"first_air_date_year,omitempty" json:"first_air_date_year,omitempty"`
	FirstAirDateGte          *openapi_types.Date     `form:"first_air_date.gte,omitempty" json:"first_air_date.gte,omitempty"`
	FirstAirDateLte          *openapi_types.Date     `form:"first_air_date.lte,omitempty" json:"first_air_date.lte,omitempty"`
	IncludeAdult             *bool                   `form:"include_adult,omitempty" json:"include_adult,omitempty"`
	IncludeNullFirstAirDates *bool                   `form:"include_null_first_air_dates,omitempty" json:"include_null_first_air_dates,omitempty"`
	Language                 *string                 `form:"language,omitempty" json:"language,omitempty"`
	Page                     *int32                  `form:"page,omitempty" json:"page,omitempty"`
	ScreenedTheatrically     *bool                   `form:"screened_theatrically,omitempty" json:"screened_theatrically,omitempty"`
	SortBy                   *DiscoverTvParamsSortBy `form:"sort_by,omitempty" json:"sort_by,omitempty"`
	Timezone                 *string                 `form:"timezone,omitempty" json:"timezone,omitempty"`
	VoteAverageGte           *float32                `form:"vote_average.gte,omitempty" json:"vote_average.gte,omitempty"`
	VoteAverageLte           *float32                `form:"vote_average.lte,omitempty" json:"vote_average.lte,omitempty"`
	VoteCountGte             *float32                `form:"vote_count.gte,omitempty" json:"vote_count.gte,omitempty"`
	VoteCountLte             *float32                `form:"vote_count.lte,omitempty" json:"vote_count.lte,omitempty"`

	// WatchRegion use in conjunction with `with_watch_monetization_types ` or `with_watch_providers `
	WatchRegion *string `form:"watch_region,omitempty" json:"watch_region,omitempty"`

	// WithCompanies can be a comma (`AND`) or pipe (`OR`) separated query
	WithCompanies *string `form:"with_companies,omitempty" json:"with_companies,omitempty"`

	// WithGenres can be a comma (`AND`) or pipe (`OR`) separated query
	WithGenres *string `form:"with_genres,omitempty" json:"with_genres,omitempty"`

	// WithKeywords can be a comma (`AND`) or pipe (`OR`) separated query
	WithKeywords         *string `form:"with_keywords,omitempty" json:"with_keywords,omitempty"`
	WithNetworks         *int32  `form:"with_networks,omitempty" json:"with_networks,omitempty"`
	WithOriginCountry    *string `form:"with_origin_country,omitempty" json:"with_origin_country,omitempty"`
	WithOriginalLanguage *string `form:"with_original_language,omitempty" json:"with_original_language,omitempty"`
	WithRuntimeGte       *int32  `form:"with_runtime.gte,omitempty" json:"with_runtime.gte,omitempty"`
	WithRuntimeLte       *int32  `form:"with_runtime.lte,omitempty" json:"with_runtime.lte,omitempty"`

	// WithStatus possible values are: [0, 1, 2, 3, 4, 5], can be a comma (`AND`) or pipe (`OR`) separated query
	WithStatus *string `form:"with_status,omitempty" json:"with_status,omitempty"`

	// WithWatchMonetizationTypes possible values are: [flatrate, free, ads, rent, buy] use in conjunction with `watch_region`, can be a comma (`AND`) or pipe (`OR`) separated query
	WithWatchMonetizationTypes *string `form:"with_watch_monetization_types,omitempty" json:"with_watch_monetization_types,omitempty"`

	// WithWatchProviders use in conjunction with `watch_region`, can be a comma (`AND`) or pipe (`OR`) separated query
	WithWatchProviders    *string `form:"with_watch_providers,omitempty" json:"with_watch_providers,omitempty"`
	WithoutCompanies      *string `form:"without_companies,omitempty" json:"without_companies,omitempty"`
	WithoutGenres         *string `form:"without_genres,omitempty" json:"without_genres,omitempty"`
	WithoutKeywords       *string `form:"without_keywords,omitempty" json:"without_keywords,omitempty"`
	WithoutWatchProviders *string `form:"without_watch_providers,omitempty" json:"without_watch_providers,omitempty"`

	// WithType possible values are: [0, 1, 2, 3, 4, 5, 6], can be a comma (`AND`) or pipe (`OR`) separated query
	WithType *string `form:"with_type,omitempty" json:"with_type,omitempty"`
}

// DiscoverTvParamsSortBy defines parameters for DiscoverTv.
type DiscoverTvParamsSortBy string

// FindByIdParams defines parameters for FindById.
type FindByIdParams struct {
	ExternalSource FindByIdParamsExternalSource `form:"external_source" json:"external_source"`
	Language       *string                      `form:"language,omitempty" json:"language,omitempty"`
}

// FindByIdParamsExternalSource defines parameters for FindById.
type FindByIdParamsExternalSource string

// GenreMovieListParams defines parameters for GenreMovieList.
type GenreMovieListParams struct {
	Language *string `form:"language,omitempty" json:"language,omitempty"`
}

// GenreTvListParams defines parameters for GenreTvList.
type GenreTvListParams struct {
	Language *string `form:"language,omitempty" json:"language,omitempty"`
}

// GuestSessionRatedMoviesParams defines parameters for GuestSessionRatedMovies.
type GuestSessionRatedMoviesParams struct {
	Language *string                              `form:"language,omitempty" json:"language,omitempty"`
	Page     *int32                               `form:"page,omitempty" json:"page,omitempty"`
	SortBy   *GuestSessionRatedMoviesParamsSortBy `form:"sort_by,omitempty" json:"sort_by,omitempty"`
}

// GuestSessionRatedMoviesParamsSortBy defines parameters for GuestSessionRatedMovies.
type GuestSessionRatedMoviesParamsSortBy string

// GuestSessionRatedTvParams defines parameters for GuestSessionRatedTv.
type GuestSessionRatedTvParams struct {
	Language *string                          `form:"language,omitempty" json:"language,omitempty"`
	Page     *int32                           `form:"page,omitempty" json:"page,omitempty"`
	SortBy   *GuestSessionRatedTvParamsSortBy `form:"sort_by,omitempty" json:"sort_by,omitempty"`
}

// GuestSessionRatedTvParamsSortBy defines parameters for GuestSessionRatedTv.
type GuestSessionRatedTvParamsSortBy string

// GuestSessionRatedTvEpisodesParams defines parameters for GuestSessionRatedTvEpisodes.
type GuestSessionRatedTvEpisodesParams struct {
	Language *string                                  `form:"language,omitempty" json:"language,omitempty"`
	Page     *int32                                   `form:"page,omitempty" json:"page,omitempty"`
	SortBy   *GuestSessionRatedTvEpisodesParamsSortBy `form:"sort_by,omitempty" json:"sort_by,omitempty"`
}

// GuestSessionRatedTvEpisodesParamsSortBy defines parameters for GuestSessionRatedTvEpisodes.
type GuestSessionRatedTvEpisodesParamsSortBy string

// KeywordMoviesParams defines parameters for KeywordMovies.
type KeywordMoviesParams struct {
	IncludeAdult *bool   `form:"include_adult,omitempty" json:"include_adult,omitempty"`
	Language     *string `form:"language,omitempty" json:"language,omitempty"`
	Page         *int32  `form:"page,omitempty" json:"page,omitempty"`
}

// ListCreateJSONBody defines parameters for ListCreate.
type ListCreateJSONBody struct {
	Description *string `json:"description,omitempty"`
	Language    *string `json:"language,omitempty"`
	Name        *string `json:"name,omitempty"`
}

// ListCreateParams defines parameters for ListCreate.
type ListCreateParams struct {
	SessionId string `form:"session_id" json:"session_id"`
}

// ListDeleteParams defines parameters for ListDelete.
type ListDeleteParams struct {
	SessionId string `form:"session_id" json:"session_id"`
}

// ListDetailsParams defines parameters for ListDetails.
type ListDetailsParams struct {
	Language *string `form:"language,omitempty" json:"language,omitempty"`
	Page     *int32  `form:"page,omitempty" json:"page,omitempty"`
}

// ListAddMovieJSONBody defines parameters for ListAddMovie.
type ListAddMovieJSONBody struct {
	MediaId *int `json:"media_id,omitempty"`
}

// ListAddMovieParams defines parameters for ListAddMovie.
type ListAddMovieParams struct {
	SessionId string `form:"session_id" json:"session_id"`
}

// ListClearParams defines parameters for ListClear.
type ListClearParams struct {
	SessionId string `form:"session_id" json:"session_id"`
	Confirm   bool   `form:"confirm" json:"confirm"`
}

// ListCheckItemStatusParams defines parameters for ListCheckItemStatus.
type ListCheckItemStatusParams struct {
	Language *string `form:"language,omitempty" json:"language,omitempty"`
	MovieId  *int32  `form:"movie_id,omitempty" json:"movie_id,omitempty"`
}

// ListRemoveMovieJSONBody defines parameters for ListRemoveMovie.
type ListRemoveMovieJSONBody struct {
	MediaId *int `json:"media_id,omitempty"`
}

// ListRemoveMovieParams defines parameters for ListRemoveMovie.
type ListRemoveMovieParams struct {
	SessionId string `form:"session_id" json:"session_id"`
}

// ChangesMovieListParams defines parameters for ChangesMovieList.
type ChangesMovieListParams struct {
	EndDate   *openapi_types.Date `form:"end_date,omitempty" json:"end_date,omitempty"`
	Page      *int32              `form:"page,omitempty" json:"page,omitempty"`
	StartDate *openapi_types.Date `form:"start_date,omitempty" json:"start_date,omitempty"`
}

// MovieNowPlayingListParams defines parameters for MovieNowPlayingList.
type MovieNowPlayingListParams struct {
	Language *string `form:"language,omitempty" json:"language,omitempty"`
	Page     *int32  `form:"page,omitempty" json:"page,omitempty"`

	// Region ISO-3166-1 code
	Region *string `form:"region,omitempty" json:"region,omitempty"`
}

// MoviePopularListParams defines parameters for MoviePopularList.
type MoviePopularListParams struct {
	Language *string `form:"language,omitempty" json:"language,omitempty"`
	Page     *int32  `form:"page,omitempty" json:"page,omitempty"`

	// Region ISO-3166-1 code
	Region *string `form:"region,omitempty" json:"region,omitempty"`
}

// MovieTopRatedListParams defines parameters for MovieTopRatedList.
type MovieTopRatedListParams struct {
	Language *string `form:"language,omitempty" json:"language,omitempty"`
	Page     *int32  `form:"page,omitempty" json:"page,omitempty"`

	// Region ISO-3166-1 code
	Region *string `form:"region,omitempty" json:"region,omitempty"`
}

// MovieUpcomingListParams defines parameters for MovieUpcomingList.
type MovieUpcomingListParams struct {
	Language *string `form:"language,omitempty" json:"language,omitempty"`
	Page     *int32  `form:"page,omitempty" json:"page,omitempty"`

	// Region ISO-3166-1 code
	Region *string `form:"region,omitempty" json:"region,omitempty"`
}

// MovieDetailsParams defines parameters for MovieDetails.
type MovieDetailsParams struct {
	// AppendToResponse comma separated list of endpoints within this namespace, 20 items max
	AppendToResponse *string `form:"append_to_response,omitempty" json:"append_to_response,omitempty"`
	Language         *string `form:"language,omitempty" json:"language,omitempty"`
}

// MovieAccountStatesParams defines parameters for MovieAccountStates.
type MovieAccountStatesParams struct {
	SessionId      *string `form:"session_id,omitempty" json:"session_id,omitempty"`
	GuestSessionId *string `form:"guest_session_id,omitempty" json:"guest_session_id,omitempty"`
}

// MovieAlternativeTitlesParams defines parameters for MovieAlternativeTitles.
type MovieAlternativeTitlesParams struct {
	// Country specify a ISO-3166-1 value to filter the results
	Country *string `form:"country,omitempty" json:"country,omitempty"`
}

// MovieChangesParams defines parameters for MovieChanges.
type MovieChangesParams struct {
	EndDate   *openapi_types.Date `form:"end_date,omitempty" json:"end_date,omitempty"`
	Page      *int32              `form:"page,omitempty" json:"page,omitempty"`
	StartDate *openapi_types.Date `form:"start_date,omitempty" json:"start_date,omitempty"`
}

// MovieCreditsParams defines parameters for MovieCredits.
type MovieCreditsParams struct {
	Language *string `form:"language,omitempty" json:"language,omitempty"`
}

// MovieImagesParams defines parameters for MovieImages.
type MovieImagesParams struct {
	// IncludeImageLanguage specify a comma separated list of ISO-639-1 values to query, for example: `en,null`
	IncludeImageLanguage *string `form:"include_image_language,omitempty" json:"include_image_language,omitempty"`
	Language             *string `form:"language,omitempty" json:"language,omitempty"`
}

// MovieListsParams defines parameters for MovieLists.
type MovieListsParams struct {
	Language *string `form:"language,omitempty" json:"language,omitempty"`
	Page     *int32  `form:"page,omitempty" json:"page,omitempty"`
}

// MovieDeleteRatingParams defines parameters for MovieDeleteRating.
type MovieDeleteRatingParams struct {
	GuestSessionId *string `form:"guest_session_id,omitempty" json:"guest_session_id,omitempty"`
	SessionId      *string `form:"session_id,omitempty" json:"session_id,omitempty"`
	ContentType    *string `json:"Content-Type,omitempty"`
}

// MovieAddRatingJSONBody defines parameters for MovieAddRating.
type MovieAddRatingJSONBody struct {
	Value *float32 `json:"value,omitempty"`
}

// MovieAddRatingParams defines parameters for MovieAddRating.
type MovieAddRatingParams struct {
	GuestSessionId *string `form:"guest_session_id,omitempty" json:"guest_session_id,omitempty"`
	SessionId      *string `form:"session_id,omitempty" json:"session_id,omitempty"`
	ContentType    string  `json:"Content-Type"`
}

// MovieRecommendationsParams defines parameters for MovieRecommendations.
type MovieRecommendationsParams struct {
	Language *string `form:"language,omitempty" json:"language,omitempty"`
	Page     *int32  `form:"page,omitempty" json:"page,omitempty"`
}

// MovieReviewsParams defines parameters for MovieReviews.
type MovieReviewsParams struct {
	Language *string `form:"language,omitempty" json:"language,omitempty"`
	Page     *int32  `form:"page,omitempty" json:"page,omitempty"`
}

// MovieSimilarParams defines parameters for MovieSimilar.
type MovieSimilarParams struct {
	Language *string `form:"language,omitempty" json:"language,omitempty"`
	Page     *int32  `form:"page,omitempty" json:"page,omitempty"`
}

// MovieVideosParams defines parameters for MovieVideos.
type MovieVideosParams struct {
	Language *string `form:"language,omitempty" json:"language,omitempty"`
}

// ChangesPeopleListParams defines parameters for ChangesPeopleList.
type ChangesPeopleListParams struct {
	EndDate   *openapi_types.Date `form:"end_date,omitempty" json:"end_date,omitempty"`
	Page      *int32              `form:"page,omitempty" json:"page,omitempty"`
	StartDate *openapi_types.Date `form:"start_date,omitempty" json:"start_date,omitempty"`
}

// PersonPopularListParams defines parameters for PersonPopularList.
type PersonPopularListParams struct {
	Language *string `form:"language,omitempty" json:"language,omitempty"`
	Page     *int32  `form:"page,omitempty" json:"page,omitempty"`
}

// PersonDetailsParams defines parameters for PersonDetails.
type PersonDetailsParams struct {
	// AppendToResponse comma separated list of endpoints within this namespace, 20 items max
	AppendToResponse *string `form:"append_to_response,omitempty" json:"append_to_response,omitempty"`
	Language         *string `form:"language,omitempty" json:"language,omitempty"`
}

// PersonChangesParams defines parameters for PersonChanges.
type PersonChangesParams struct {
	EndDate   *openapi_types.Date `form:"end_date,omitempty" json:"end_date,omitempty"`
	Page      *int32              `form:"page,omitempty" json:"page,omitempty"`
	StartDate *openapi_types.Date `form:"start_date,omitempty" json:"start_date,omitempty"`
}

// PersonCombinedCreditsParams defines parameters for PersonCombinedCredits.
type PersonCombinedCreditsParams struct {
	Language *string `form:"language,omitempty" json:"language,omitempty"`
}

// PersonMovieCreditsParams defines parameters for PersonMovieCredits.
type PersonMovieCreditsParams struct {
	Language *string `form:"language,omitempty" json:"language,omitempty"`
}

// PersonTaggedImagesParams defines parameters for PersonTaggedImages.
type PersonTaggedImagesParams struct {
	Page *int32 `form:"page,omitempty" json:"page,omitempty"`
}

// PersonTvCreditsParams defines parameters for PersonTvCredits.
type PersonTvCreditsParams struct {
	Language *string `form:"language,omitempty" json:"language,omitempty"`
}

// SearchCollectionParams defines parameters for SearchCollection.
type SearchCollectionParams struct {
	Query        string  `form:"query" json:"query"`
	IncludeAdult *bool   `form:"include_adult,omitempty" json:"include_adult,omitempty"`
	Language     *string `form:"language,omitempty" json:"language,omitempty"`
	Page         *int32  `form:"page,omitempty" json:"page,omitempty"`
	Region       *string `form:"region,omitempty" json:"region,omitempty"`
}

// SearchCompanyParams defines parameters for SearchCompany.
type SearchCompanyParams struct {
	Query string `form:"query" json:"query"`
	Page  *int32 `form:"page,omitempty" json:"page,omitempty"`
}

// SearchKeywordParams defines parameters for SearchKeyword.
type SearchKeywordParams struct {
	Query string `form:"query" json:"query"`
	Page  *int32 `form:"page,omitempty" json:"page,omitempty"`
}

// SearchMovieParams defines parameters for SearchMovie.
type SearchMovieParams struct {
	Query              string  `form:"query" json:"query"`
	IncludeAdult       *bool   `form:"include_adult,omitempty" json:"include_adult,omitempty"`
	Language           *string `form:"language,omitempty" json:"language,omitempty"`
	PrimaryReleaseYear *string `form:"primary_release_year,omitempty" json:"primary_release_year,omitempty"`
	Page               *int32  `form:"page,omitempty" json:"page,omitempty"`
	Region             *string `form:"region,omitempty" json:"region,omitempty"`
	Year               *string `form:"year,omitempty" json:"year,omitempty"`
}

// SearchMultiParams defines parameters for SearchMulti.
type SearchMultiParams struct {
	Query        string  `form:"query" json:"query"`
	IncludeAdult *bool   `form:"include_adult,omitempty" json:"include_adult,omitempty"`
	Language     *string `form:"language,omitempty" json:"language,omitempty"`
	Page         *int32  `form:"page,omitempty" json:"page,omitempty"`
}

// SearchPersonParams defines parameters for SearchPerson.
type SearchPersonParams struct {
	Query        string  `form:"query" json:"query"`
	IncludeAdult *bool   `form:"include_adult,omitempty" json:"include_adult,omitempty"`
	Language     *string `form:"language,omitempty" json:"language,omitempty"`
	Page         *int32  `form:"page,omitempty" json:"page,omitempty"`
}

// SearchTvParams defines parameters for SearchTv.
type SearchTvParams struct {
	Query string `form:"query" json:"query"`

	// FirstAirDateYear Search only the first air date. Valid values are: 1000..9999
	FirstAirDateYear *int32  `form:"first_air_date_year,omitempty" json:"first_air_date_year,omitempty"`
	IncludeAdult     *bool   `form:"include_adult,omitempty" json:"include_adult,omitempty"`
	Language         *string `form:"language,omitempty" json:"language,omitempty"`
	Page             *int32  `form:"page,omitempty" json:"page,omitempty"`

	// Year Search the first air date and all episode air dates. Valid values are: 1000..9999
	Year *int32 `form:"year,omitempty" json:"year,omitempty"`
}

// TrendingAllParams defines parameters for TrendingAll.
type TrendingAllParams struct {
	// Language `ISO-639-1`-`ISO-3166-1` code
	Language *string `form:"language,omitempty" json:"language,omitempty"`
}

// TrendingAllParamsTimeWindow defines parameters for TrendingAll.
type TrendingAllParamsTimeWindow string

// TrendingMoviesParams defines parameters for TrendingMovies.
type TrendingMoviesParams struct {
	// Language `ISO-639-1`-`ISO-3166-1` code
	Language *string `form:"language,omitempty" json:"language,omitempty"`
}

// TrendingMoviesParamsTimeWindow defines parameters for TrendingMovies.
type TrendingMoviesParamsTimeWindow string

// TrendingPeopleParams defines parameters for TrendingPeople.
type TrendingPeopleParams struct {
	// Language `ISO-639-1`-`ISO-3166-1` code
	Language *string `form:"language,omitempty" json:"language,omitempty"`
}

// TrendingPeopleParamsTimeWindow defines parameters for TrendingPeople.
type TrendingPeopleParamsTimeWindow string

// TrendingTvParams defines parameters for TrendingTv.
type TrendingTvParams struct {
	// Language `ISO-639-1`-`ISO-3166-1` code
	Language *string `form:"language,omitempty" json:"language,omitempty"`
}

// TrendingTvParamsTimeWindow defines parameters for TrendingTv.
type TrendingTvParamsTimeWindow string

// TvSeriesAiringTodayListParams defines parameters for TvSeriesAiringTodayList.
type TvSeriesAiringTodayListParams struct {
	Language *string `form:"language,omitempty" json:"language,omitempty"`
	Page     *int32  `form:"page,omitempty" json:"page,omitempty"`
	Timezone *string `form:"timezone,omitempty" json:"timezone,omitempty"`
}

// ChangesTvListParams defines parameters for ChangesTvList.
type ChangesTvListParams struct {
	EndDate   *openapi_types.Date `form:"end_date,omitempty" json:"end_date,omitempty"`
	Page      *int32              `form:"page,omitempty" json:"page,omitempty"`
	StartDate *openapi_types.Date `form:"start_date,omitempty" json:"start_date,omitempty"`
}

// TvSeriesOnTheAirListParams defines parameters for TvSeriesOnTheAirList.
type TvSeriesOnTheAirListParams struct {
	Language *string `form:"language,omitempty" json:"language,omitempty"`
	Page     *int32  `form:"page,omitempty" json:"page,omitempty"`
	Timezone *string `form:"timezone,omitempty" json:"timezone,omitempty"`
}

// TvSeriesPopularListParams defines parameters for TvSeriesPopularList.
type TvSeriesPopularListParams struct {
	Language *string `form:"language,omitempty" json:"language,omitempty"`
	Page     *int32  `form:"page,omitempty" json:"page,omitempty"`
}

// TvSeasonChangesByIdParams defines parameters for TvSeasonChangesById.
type TvSeasonChangesByIdParams struct {
	EndDate   *string `form:"end_date,omitempty" json:"end_date,omitempty"`
	Page      *int32  `form:"page,omitempty" json:"page,omitempty"`
	StartDate *string `form:"start_date,omitempty" json:"start_date,omitempty"`
}

// TvSeriesTopRatedListParams defines parameters for TvSeriesTopRatedList.
type TvSeriesTopRatedListParams struct {
	Language *string `form:"language,omitempty" json:"language,omitempty"`
	Page     *int32  `form:"page,omitempty" json:"page,omitempty"`
}

// TvSeriesDetailsParams defines parameters for TvSeriesDetails.
type TvSeriesDetailsParams struct {
	// AppendToResponse comma separated list of endpoints within this namespace, 20 items max
	AppendToResponse *string `form:"append_to_response,omitempty" json:"append_to_response,omitempty"`
	Language         *string `form:"language,omitempty" json:"language,omitempty"`
}

// TvSeriesAccountStatesParams defines parameters for TvSeriesAccountStates.
type TvSeriesAccountStatesParams struct {
	SessionId      *string `form:"session_id,omitempty" json:"session_id,omitempty"`
	GuestSessionId *string `form:"guest_session_id,omitempty" json:"guest_session_id,omitempty"`
}

// TvSeriesAggregateCreditsParams defines parameters for TvSeriesAggregateCredits.
type TvSeriesAggregateCreditsParams struct {
	Language *string `form:"language,omitempty" json:"language,omitempty"`
}

// TvSeriesChangesParams defines parameters for TvSeriesChanges.
type TvSeriesChangesParams struct {
	EndDate   *string `form:"end_date,omitempty" json:"end_date,omitempty"`
	Page      *int32  `form:"page,omitempty" json:"page,omitempty"`
	StartDate *string `form:"start_date,omitempty" json:"start_date,omitempty"`
}

// TvSeriesCreditsParams defines parameters for TvSeriesCredits.
type TvSeriesCreditsParams struct {
	Language *string `form:"language,omitempty" json:"language,omitempty"`
}

// TvSeriesImagesParams defines parameters for TvSeriesImages.
type TvSeriesImagesParams struct {
	// IncludeImageLanguage specify a comma separated list of ISO-639-1 values to query, for example: `en,null`
	IncludeImageLanguage *string `form:"include_image_language,omitempty" json:"include_image_language,omitempty"`
	Language             *string `form:"language,omitempty" json:"language,omitempty"`
}

// ListsCopyParams defines parameters for ListsCopy.
type ListsCopyParams struct {
	Language *string `form:"language,omitempty" json:"language,omitempty"`
	Page     *int32  `form:"page,omitempty" json:"page,omitempty"`
}

// TvSeriesDeleteRatingParams defines parameters for TvSeriesDeleteRating.
type TvSeriesDeleteRatingParams struct {
	GuestSessionId *string `form:"guest_session_id,omitempty" json:"guest_session_id,omitempty"`
	SessionId      *string `form:"session_id,omitempty" json:"session_id,omitempty"`
	ContentType    *string `json:"Content-Type,omitempty"`
}

// TvSeriesAddRatingJSONBody defines parameters for TvSeriesAddRating.
type TvSeriesAddRatingJSONBody struct {
	Value *float32 `json:"value,omitempty"`
}

// TvSeriesAddRatingParams defines parameters for TvSeriesAddRating.
type TvSeriesAddRatingParams struct {
	GuestSessionId *string `form:"guest_session_id,omitempty" json:"guest_session_id,omitempty"`
	SessionId      *string `form:"session_id,omitempty" json:"session_id,omitempty"`
	ContentType    string  `json:"Content-Type"`
}

// TvSeriesRecommendationsParams defines parameters for TvSeriesRecommendations.
type TvSeriesRecommendationsParams struct {
	Language *string `form:"language,omitempty" json:"language,omitempty"`
	Page     *int32  `form:"page,omitempty" json:"page,omitempty"`
}

// TvSeriesReviewsParams defines parameters for TvSeriesReviews.
type TvSeriesReviewsParams struct {
	Language *string `form:"language,omitempty" json:"language,omitempty"`
	Page     *int32  `form:"page,omitempty" json:"page,omitempty"`
}

// TvSeasonDetailsParams defines parameters for TvSeasonDetails.
type TvSeasonDetailsParams struct {
	// AppendToResponse comma separated list of endpoints within this namespace, 20 items max
	AppendToResponse *string `form:"append_to_response,omitempty" json:"append_to_response,omitempty"`
	Language         *string `form:"language,omitempty" json:"language,omitempty"`
}

// TvSeasonAccountStatesParams defines parameters for TvSeasonAccountStates.
type TvSeasonAccountStatesParams struct {
	SessionId      *string `form:"session_id,omitempty" json:"session_id,omitempty"`
	GuestSessionId *string `form:"guest_session_id,omitempty" json:"guest_session_id,omitempty"`
}

// TvSeasonAggregateCreditsParams defines parameters for TvSeasonAggregateCredits.
type TvSeasonAggregateCreditsParams struct {
	Language *string `form:"language,omitempty" json:"language,omitempty"`
}

// TvSeasonCreditsParams defines parameters for TvSeasonCredits.
type TvSeasonCreditsParams struct {
	Language *string `form:"language,omitempty" json:"language,omitempty"`
}

// TvEpisodeDetailsParams defines parameters for TvEpisodeDetails.
type TvEpisodeDetailsParams struct {
	// AppendToResponse comma separated list of endpoints within this namespace, 20 items max
	AppendToResponse *string `form:"append_to_response,omitempty" json:"append_to_response,omitempty"`
	Language         *string `form:"language,omitempty" json:"language,omitempty"`
}

// TvEpisodeAccountStatesParams defines parameters for TvEpisodeAccountStates.
type TvEpisodeAccountStatesParams struct {
	SessionId      *string `form:"session_id,omitempty" json:"session_id,omitempty"`
	GuestSessionId *string `form:"guest_session_id,omitempty" json:"guest_session_id,omitempty"`
}

// TvEpisodeCreditsParams defines parameters for TvEpisodeCredits.
type TvEpisodeCreditsParams struct {
	Language *string `form:"language,omitempty" json:"language,omitempty"`
}

// TvEpisodeImagesParams defines parameters for TvEpisodeImages.
type TvEpisodeImagesParams struct {
	// IncludeImageLanguage specify a comma separated list of ISO-639-1 values to query, for example: `en,null`
	IncludeImageLanguage *string `form:"include_image_language,omitempty" json:"include_image_language,omitempty"`
	Language             *string `form:"language,omitempty" json:"language,omitempty"`
}

// TvEpisodeDeleteRatingParams defines parameters for TvEpisodeDeleteRating.
type TvEpisodeDeleteRatingParams struct {
	GuestSessionId *string `form:"guest_session_id,omitempty" json:"guest_session_id,omitempty"`
	SessionId      *string `form:"session_id,omitempty" json:"session_id,omitempty"`
	ContentType    *string `json:"Content-Type,omitempty"`
}

// TvEpisodeAddRatingJSONBody defines parameters for TvEpisodeAddRating.
type TvEpisodeAddRatingJSONBody struct {
	Value *float32 `json:"value,omitempty"`
}

// TvEpisodeAddRatingParams defines parameters for TvEpisodeAddRating.
type TvEpisodeAddRatingParams struct {
	GuestSessionId *string `form:"guest_session_id,omitempty" json:"guest_session_id,omitempty"`
	SessionId      *string `form:"session_id,omitempty" json:"session_id,omitempty"`
	ContentType    string  `json:"Content-Type"`
}

// TvEpisodeVideosParams defines parameters for TvEpisodeVideos.
type TvEpisodeVideosParams struct {
	// IncludeVideoLanguage filter the list results by language, supports more than one value by using a comma
	IncludeVideoLanguage *string `form:"include_video_language,omitempty" json:"include_video_language,omitempty"`
	Language             *string `form:"language,omitempty" json:"language,omitempty"`
}

// TvSeasonImagesParams defines parameters for TvSeasonImages.
type TvSeasonImagesParams struct {
	// IncludeImageLanguage specify a comma separated list of ISO-639-1 values to query, for example: `en,null`
	IncludeImageLanguage *string `form:"include_image_language,omitempty" json:"include_image_language,omitempty"`
	Language             *string `form:"language,omitempty" json:"language,omitempty"`
}

// TvSeasonVideosParams defines parameters for TvSeasonVideos.
type TvSeasonVideosParams struct {
	// IncludeVideoLanguage filter the list results by language, supports more than one value by using a comma
	IncludeVideoLanguage *string `form:"include_video_language,omitempty" json:"include_video_language,omitempty"`
	Language             *string `form:"language,omitempty" json:"language,omitempty"`
}

// TvSeasonWatchProvidersParams defines parameters for TvSeasonWatchProviders.
type TvSeasonWatchProvidersParams struct {
	Language *string `form:"language,omitempty" json:"language,omitempty"`
}

// TvSeriesSimilarParams defines parameters for TvSeriesSimilar.
type TvSeriesSimilarParams struct {
	Language *string `form:"language,omitempty" json:"language,omitempty"`
	Page     *int32  `form:"page,omitempty" json:"page,omitempty"`
}

// TvSeriesVideosParams defines parameters for TvSeriesVideos.
type TvSeriesVideosParams struct {
	// IncludeVideoLanguage filter the list results by language, supports more than one value by using a comma
	IncludeVideoLanguage *string `form:"include_video_language,omitempty" json:"include_video_language,omitempty"`
	Language             *string `form:"language,omitempty" json:"language,omitempty"`
}

// WatchProvidersMovieListParams defines parameters for WatchProvidersMovieList.
type WatchProvidersMovieListParams struct {
	Language    *string `form:"language,omitempty" json:"language,omitempty"`
	WatchRegion *string `form:"watch_region,omitempty" json:"watch_region,omitempty"`
}

// WatchProvidersAvailableRegionsParams defines parameters for WatchProvidersAvailableRegions.
type WatchProvidersAvailableRegionsParams struct {
	Language *string `form:"language,omitempty" json:"language,omitempty"`
}

// WatchProviderTvListParams defines parameters for WatchProviderTvList.
type WatchProviderTvListParams struct {
	Language    *string `form:"language,omitempty" json:"language,omitempty"`
	WatchRegion *string `form:"watch_region,omitempty" json:"watch_region,omitempty"`
}

// AccountAddFavoriteJSONRequestBody defines body for AccountAddFavorite for application/json ContentType.
type AccountAddFavoriteJSONRequestBody AccountAddFavoriteJSONBody

// AccountAddToWatchlistJSONRequestBody defines body for AccountAddToWatchlist for application/json ContentType.
type AccountAddToWatchlistJSONRequestBody AccountAddToWatchlistJSONBody

// AuthenticationDeleteSessionJSONRequestBody defines body for AuthenticationDeleteSession for application/json ContentType.
type AuthenticationDeleteSessionJSONRequestBody AuthenticationDeleteSessionJSONBody

// AuthenticationCreateSessionFromV4TokenJSONRequestBody defines body for AuthenticationCreateSessionFromV4Token for application/json ContentType.
type AuthenticationCreateSessionFromV4TokenJSONRequestBody AuthenticationCreateSessionFromV4TokenJSONBody

// AuthenticationCreateSessionJSONRequestBody defines body for AuthenticationCreateSession for application/json ContentType.
type AuthenticationCreateSessionJSONRequestBody AuthenticationCreateSessionJSONBody

// AuthenticationCreateSessionFromLoginJSONRequestBody defines body for AuthenticationCreateSessionFromLogin for application/json ContentType.
type AuthenticationCreateSessionFromLoginJSONRequestBody AuthenticationCreateSessionFromLoginJSONBody

// ListCreateJSONRequestBody defines body for ListCreate for application/json ContentType.
type ListCreateJSONRequestBody ListCreateJSONBody

// ListAddMovieJSONRequestBody defines body for ListAddMovie for application/json ContentType.
type ListAddMovieJSONRequestBody ListAddMovieJSONBody

// ListRemoveMovieJSONRequestBody defines body for ListRemoveMovie for application/json ContentType.
type ListRemoveMovieJSONRequestBody ListRemoveMovieJSONBody

// MovieAddRatingJSONRequestBody defines body for MovieAddRating for application/json ContentType.
type MovieAddRatingJSONRequestBody MovieAddRatingJSONBody

// TvSeriesAddRatingJSONRequestBody defines body for TvSeriesAddRating for application/json ContentType.
type TvSeriesAddRatingJSONRequestBody TvSeriesAddRatingJSONBody

// TvEpisodeAddRatingJSONRequestBody defines body for TvEpisodeAddRating for application/json ContentType.
type TvEpisodeAddRatingJSONRequestBody TvEpisodeAddRatingJSONBody
