// Code generated by ogen, DO NOT EDIT.

package tmdb

// AccountAddFavoriteParams is parameters of account-add-favorite operation.
type AccountAddFavoriteParams struct {
	AccountID NilInt32
	SessionID OptString
}

// AccountAddToWatchlistParams is parameters of account-add-to-watchlist operation.
type AccountAddToWatchlistParams struct {
	AccountID NilInt32
	SessionID OptString
}

// AccountDetailsParams is parameters of account-details operation.
type AccountDetailsParams struct {
	AccountID NilInt32
	SessionID OptString
}

// AccountFavoriteTvParams is parameters of account-favorite-tv operation.
type AccountFavoriteTvParams struct {
	AccountID NilInt32
	Language  OptString
	Page      OptInt32
	SessionID OptString
	SortBy    OptAccountFavoriteTvSortBy
}

// AccountGetFavoritesParams is parameters of account-get-favorites operation.
type AccountGetFavoritesParams struct {
	AccountID NilInt32
	Language  OptString
	Page      OptInt32
	SessionID OptString
	SortBy    OptAccountGetFavoritesSortBy
}

// AccountListsParams is parameters of account-lists operation.
type AccountListsParams struct {
	AccountID NilInt32
	Page      OptInt32
	SessionID OptString
}

// AccountRatedMoviesParams is parameters of account-rated-movies operation.
type AccountRatedMoviesParams struct {
	AccountID NilInt32
	Language  OptString
	Page      OptInt32
	SessionID OptString
	SortBy    OptAccountRatedMoviesSortBy
}

// AccountRatedTvParams is parameters of account-rated-tv operation.
type AccountRatedTvParams struct {
	AccountID NilInt32
	Language  OptString
	Page      OptInt32
	SessionID OptString
	SortBy    OptAccountRatedTvSortBy
}

// AccountRatedTvEpisodesParams is parameters of account-rated-tv-episodes operation.
type AccountRatedTvEpisodesParams struct {
	AccountID NilInt32
	Language  OptString
	Page      OptInt32
	SessionID OptString
	SortBy    OptAccountRatedTvEpisodesSortBy
}

// AccountWatchlistMoviesParams is parameters of account-watchlist-movies operation.
type AccountWatchlistMoviesParams struct {
	AccountID NilInt32
	Language  OptString
	Page      OptInt32
	SessionID OptString
	SortBy    OptAccountWatchlistMoviesSortBy
}

// AccountWatchlistTvParams is parameters of account-watchlist-tv operation.
type AccountWatchlistTvParams struct {
	AccountID NilInt32
	Language  OptString
	Page      OptInt32
	SessionID OptString
	SortBy    OptAccountWatchlistTvSortBy
}

// AlternativeNamesCopyParams is parameters of alternative-names-copy operation.
type AlternativeNamesCopyParams struct {
	NetworkID int32
}

// ChangesMovieListParams is parameters of changes-movie-list operation.
type ChangesMovieListParams struct {
	EndDate   OptDate
	Page      OptInt32
	StartDate OptDate
}

// ChangesPeopleListParams is parameters of changes-people-list operation.
type ChangesPeopleListParams struct {
	EndDate   OptDate
	Page      OptInt32
	StartDate OptDate
}

// ChangesTvListParams is parameters of changes-tv-list operation.
type ChangesTvListParams struct {
	EndDate   OptDate
	Page      OptInt32
	StartDate OptDate
}

// CollectionDetailsParams is parameters of collection-details operation.
type CollectionDetailsParams struct {
	CollectionID int32
	Language     OptString
}

// CollectionImagesParams is parameters of collection-images operation.
type CollectionImagesParams struct {
	CollectionID int32
	// Specify a comma separated list of ISO-639-1 values to query, for example: `en,null`.
	IncludeImageLanguage OptString
	Language             OptString
}

// CollectionTranslationsParams is parameters of collection-translations operation.
type CollectionTranslationsParams struct {
	CollectionID int32
}

// CompanyAlternativeNamesParams is parameters of company-alternative-names operation.
type CompanyAlternativeNamesParams struct {
	CompanyID int32
}

// CompanyDetailsParams is parameters of company-details operation.
type CompanyDetailsParams struct {
	CompanyID int32
}

// CompanyImagesParams is parameters of company-images operation.
type CompanyImagesParams struct {
	CompanyID int32
}

// ConfigurationCountriesParams is parameters of configuration-countries operation.
type ConfigurationCountriesParams struct {
	Language OptString
}

// CreditDetailsParams is parameters of credit-details operation.
type CreditDetailsParams struct {
	CreditID string
}

// DetailsCopyParams is parameters of details-copy operation.
type DetailsCopyParams struct {
	NetworkID int32
}

// DiscoverMovieParams is parameters of discover-movie operation.
type DiscoverMovieParams struct {
	// Use in conjunction with `region`.
	Certification OptString
	// Use in conjunction with `region`.
	CertificationGte OptString
	// Use in conjunction with `region`.
	CertificationLte OptString
	// Use in conjunction with the `certification`, `certification.gte` and `certification.lte` filters.
	CertificationCountry  OptString
	IncludeAdult          OptBool
	IncludeVideo          OptBool
	Language              OptString
	Page                  OptInt32
	PrimaryReleaseYear    OptInt32
	PrimaryReleaseDateGte OptDate
	PrimaryReleaseDateLte OptDate
	Region                OptString
	ReleaseDateGte        OptDate
	ReleaseDateLte        OptDate
	SortBy                OptDiscoverMovieSortBy
	VoteAverageGte        OptFloat32
	VoteAverageLte        OptFloat32
	VoteCountGte          OptFloat32
	VoteCountLte          OptFloat32
	WatchRegion           OptString
	// Can be a comma (`AND`) or pipe (`OR`) separated query.
	WithCast OptString
	// Can be a comma (`AND`) or pipe (`OR`) separated query.
	WithCompanies OptString
	// Can be a comma (`AND`) or pipe (`OR`) separated query.
	WithCrew OptString
	// Can be a comma (`AND`) or pipe (`OR`) separated query.
	WithGenres OptString
	// Can be a comma (`AND`) or pipe (`OR`) separated query.
	WithKeywords         OptString
	WithOriginCountry    OptString
	WithOriginalLanguage OptString
	// Can be a comma (`AND`) or pipe (`OR`) separated query.
	WithPeople OptString
	// Can be a comma (`AND`) or pipe (`OR`) separated query, can be used in conjunction with `region`.
	WithReleaseType OptInt32
	WithRuntimeGte  OptInt32
	WithRuntimeLte  OptInt32
	// Use in conjunction with `watch_region`, can be a comma (`AND`) or pipe (`OR`) separated query.
	WithWatchMonetizationTypes OptString
	// Use in conjunction with `watch_region`, can be a comma (`AND`) or pipe (`OR`) separated query.
	WithWatchProviders    OptString
	WithoutCompanies      OptString
	WithoutGenres         OptString
	WithoutKeywords       OptString
	WithoutWatchProviders OptString
	Year                  OptInt32
}

// DiscoverTvParams is parameters of discover-tv operation.
type DiscoverTvParams struct {
	AirDateGte               OptDate
	AirDateLte               OptDate
	FirstAirDateYear         OptInt32
	FirstAirDateGte          OptDate
	FirstAirDateLte          OptDate
	IncludeAdult             OptBool
	IncludeNullFirstAirDates OptBool
	Language                 OptString
	Page                     OptInt32
	ScreenedTheatrically     OptBool
	SortBy                   OptDiscoverTvSortBy
	Timezone                 OptString
	VoteAverageGte           OptFloat32
	VoteAverageLte           OptFloat32
	VoteCountGte             OptFloat32
	VoteCountLte             OptFloat32
	WatchRegion              OptString
	// Can be a comma (`AND`) or pipe (`OR`) separated query.
	WithCompanies OptString
	// Can be a comma (`AND`) or pipe (`OR`) separated query.
	WithGenres OptString
	// Can be a comma (`AND`) or pipe (`OR`) separated query.
	WithKeywords         OptString
	WithNetworks         OptInt32
	WithOriginCountry    OptString
	WithOriginalLanguage OptString
	WithRuntimeGte       OptInt32
	WithRuntimeLte       OptInt32
	// Possible values are: [0, 1, 2, 3, 4, 5], can be a comma (`AND`) or pipe (`OR`) separated query.
	WithStatus OptString
	// Possible values are: [flatrate, free, ads, rent, buy] use in conjunction with `watch_region`, can
	// be a comma (`AND`) or pipe (`OR`) separated query.
	WithWatchMonetizationTypes OptString
	// Use in conjunction with `watch_region`, can be a comma (`AND`) or pipe (`OR`) separated query.
	WithWatchProviders    OptString
	WithoutCompanies      OptString
	WithoutGenres         OptString
	WithoutKeywords       OptString
	WithoutWatchProviders OptString
	// Possible values are: [0, 1, 2, 3, 4, 5, 6], can be a comma (`AND`) or pipe (`OR`) separated query.
	WithType OptString
}

// FindByIDParams is parameters of find-by-id operation.
type FindByIDParams struct {
	ExternalID     string
	ExternalSource FindByIDExternalSource
	Language       OptString
}

// GenreMovieListParams is parameters of genre-movie-list operation.
type GenreMovieListParams struct {
	Language OptString
}

// GenreTvListParams is parameters of genre-tv-list operation.
type GenreTvListParams struct {
	Language OptString
}

// GuestSessionRatedMoviesParams is parameters of guest-session-rated-movies operation.
type GuestSessionRatedMoviesParams struct {
	GuestSessionID string
	Language       OptString
	Page           OptInt32
	SortBy         OptGuestSessionRatedMoviesSortBy
}

// GuestSessionRatedTvParams is parameters of guest-session-rated-tv operation.
type GuestSessionRatedTvParams struct {
	GuestSessionID string
	Language       OptString
	Page           OptInt32
	SortBy         OptGuestSessionRatedTvSortBy
}

// GuestSessionRatedTvEpisodesParams is parameters of guest-session-rated-tv-episodes operation.
type GuestSessionRatedTvEpisodesParams struct {
	GuestSessionID string
	Language       OptString
	Page           OptInt32
	SortBy         OptGuestSessionRatedTvEpisodesSortBy
}

// KeywordDetailsParams is parameters of keyword-details operation.
type KeywordDetailsParams struct {
	KeywordID int32
}

// KeywordMoviesParams is parameters of keyword-movies operation.
type KeywordMoviesParams struct {
	KeywordID    string
	IncludeAdult OptBool
	Language     OptString
	Page         OptInt32
}

// ListAddMovieParams is parameters of list-add-movie operation.
type ListAddMovieParams struct {
	ListID    int32
	SessionID string
}

// ListCheckItemStatusParams is parameters of list-check-item-status operation.
type ListCheckItemStatusParams struct {
	ListID   int32
	Language OptString
	MovieID  OptInt32
}

// ListClearParams is parameters of list-clear operation.
type ListClearParams struct {
	ListID    int32
	SessionID string
	Confirm   bool
}

// ListCreateParams is parameters of list-create operation.
type ListCreateParams struct {
	SessionID string
}

// ListDeleteParams is parameters of list-delete operation.
type ListDeleteParams struct {
	ListID    int32
	SessionID string
}

// ListDetailsParams is parameters of list-details operation.
type ListDetailsParams struct {
	ListID   int32
	Language OptString
	Page     OptInt32
}

// ListRemoveMovieParams is parameters of list-remove-movie operation.
type ListRemoveMovieParams struct {
	ListID    int32
	SessionID string
}

// MovieAccountStatesParams is parameters of movie-account-states operation.
type MovieAccountStatesParams struct {
	MovieID        int32
	SessionID      OptString
	GuestSessionID OptString
}

// MovieAddRatingParams is parameters of movie-add-rating operation.
type MovieAddRatingParams struct {
	MovieID        int32
	GuestSessionID OptString
	SessionID      OptString
}

// MovieAlternativeTitlesParams is parameters of movie-alternative-titles operation.
type MovieAlternativeTitlesParams struct {
	MovieID int32
	// Specify a ISO-3166-1 value to filter the results.
	Country OptString
}

// MovieChangesParams is parameters of movie-changes operation.
type MovieChangesParams struct {
	MovieID   int32
	EndDate   OptDate
	Page      OptInt32
	StartDate OptDate
}

// MovieCreditsParams is parameters of movie-credits operation.
type MovieCreditsParams struct {
	MovieID  int32
	Language OptString
}

// MovieDeleteRatingParams is parameters of movie-delete-rating operation.
type MovieDeleteRatingParams struct {
	MovieID        int32
	GuestSessionID OptString
	SessionID      OptString
}

// MovieDetailsParams is parameters of movie-details operation.
type MovieDetailsParams struct {
	MovieID int32
	// Comma separated list of endpoints within this namespace, 20 items max.
	AppendToResponse OptString
	Language         OptString
}

// MovieExternalIdsParams is parameters of movie-external-ids operation.
type MovieExternalIdsParams struct {
	MovieID int32
}

// MovieImagesParams is parameters of movie-images operation.
type MovieImagesParams struct {
	MovieID int32
	// Specify a comma separated list of ISO-639-1 values to query, for example: `en,null`.
	IncludeImageLanguage OptString
	Language             OptString
}

// MovieKeywordsParams is parameters of movie-keywords operation.
type MovieKeywordsParams struct {
	MovieID string
}

// MovieListsParams is parameters of movie-lists operation.
type MovieListsParams struct {
	MovieID  int32
	Language OptString
	Page     OptInt32
}

// MovieNowPlayingListParams is parameters of movie-now-playing-list operation.
type MovieNowPlayingListParams struct {
	Language OptString
	Page     OptInt32
	// ISO-3166-1 code.
	Region OptString
}

// MoviePopularListParams is parameters of movie-popular-list operation.
type MoviePopularListParams struct {
	Language OptString
	Page     OptInt32
	// ISO-3166-1 code.
	Region OptString
}

// MovieRecommendationsParams is parameters of movie-recommendations operation.
type MovieRecommendationsParams struct {
	MovieID  int32
	Language OptString
	Page     OptInt32
}

// MovieReleaseDatesParams is parameters of movie-release-dates operation.
type MovieReleaseDatesParams struct {
	MovieID int32
}

// MovieReviewsParams is parameters of movie-reviews operation.
type MovieReviewsParams struct {
	MovieID  int32
	Language OptString
	Page     OptInt32
}

// MovieSimilarParams is parameters of movie-similar operation.
type MovieSimilarParams struct {
	MovieID  int32
	Language OptString
	Page     OptInt32
}

// MovieTopRatedListParams is parameters of movie-top-rated-list operation.
type MovieTopRatedListParams struct {
	Language OptString
	Page     OptInt32
	// ISO-3166-1 code.
	Region OptString
}

// MovieTranslationsParams is parameters of movie-translations operation.
type MovieTranslationsParams struct {
	MovieID int32
}

// MovieUpcomingListParams is parameters of movie-upcoming-list operation.
type MovieUpcomingListParams struct {
	Language OptString
	Page     OptInt32
	// ISO-3166-1 code.
	Region OptString
}

// MovieVideosParams is parameters of movie-videos operation.
type MovieVideosParams struct {
	MovieID  int32
	Language OptString
}

// MovieWatchProvidersParams is parameters of movie-watch-providers operation.
type MovieWatchProvidersParams struct {
	MovieID int32
}

// NetworkDetailsParams is parameters of network-details operation.
type NetworkDetailsParams struct {
	NetworkID int32
}

// PersonChangesParams is parameters of person-changes operation.
type PersonChangesParams struct {
	PersonID  int32
	EndDate   OptDate
	Page      OptInt32
	StartDate OptDate
}

// PersonCombinedCreditsParams is parameters of person-combined-credits operation.
type PersonCombinedCreditsParams struct {
	PersonID string
	Language OptString
}

// PersonDetailsParams is parameters of person-details operation.
type PersonDetailsParams struct {
	PersonID int32
	// Comma separated list of endpoints within this namespace, 20 items max.
	AppendToResponse OptString
	Language         OptString
}

// PersonExternalIdsParams is parameters of person-external-ids operation.
type PersonExternalIdsParams struct {
	PersonID int32
}

// PersonImagesParams is parameters of person-images operation.
type PersonImagesParams struct {
	PersonID int32
}

// PersonMovieCreditsParams is parameters of person-movie-credits operation.
type PersonMovieCreditsParams struct {
	PersonID int32
	Language OptString
}

// PersonPopularListParams is parameters of person-popular-list operation.
type PersonPopularListParams struct {
	Language OptString
	Page     OptInt32
}

// PersonTaggedImagesParams is parameters of person-tagged-images operation.
type PersonTaggedImagesParams struct {
	PersonID int32
	Page     OptInt32
}

// PersonTvCreditsParams is parameters of person-tv-credits operation.
type PersonTvCreditsParams struct {
	PersonID int32
	Language OptString
}

// ReviewDetailsParams is parameters of review-details operation.
type ReviewDetailsParams struct {
	ReviewID string
}

// SearchCollectionParams is parameters of search-collection operation.
type SearchCollectionParams struct {
	Query        string
	IncludeAdult OptBool
	Language     OptString
	Page         OptInt32
	Region       OptString
}

// SearchCompanyParams is parameters of search-company operation.
type SearchCompanyParams struct {
	Query string
	Page  OptInt32
}

// SearchKeywordParams is parameters of search-keyword operation.
type SearchKeywordParams struct {
	Query string
	Page  OptInt32
}

// SearchMovieParams is parameters of search-movie operation.
type SearchMovieParams struct {
	Query              string
	IncludeAdult       OptBool
	Language           OptString
	PrimaryReleaseYear OptString
	Page               OptInt32
	Region             OptString
	Year               OptString
}

// SearchMultiParams is parameters of search-multi operation.
type SearchMultiParams struct {
	Query        string
	IncludeAdult OptBool
	Language     OptString
	Page         OptInt32
}

// SearchPersonParams is parameters of search-person operation.
type SearchPersonParams struct {
	Query        string
	IncludeAdult OptBool
	Language     OptString
	Page         OptInt32
}

// SearchTvParams is parameters of search-tv operation.
type SearchTvParams struct {
	Query            string
	FirstAirDateYear OptString
	IncludeAdult     OptBool
	Language         OptString
	Page             OptInt32
	Year             OptString
}

// TranslationsParams is parameters of translations operation.
type TranslationsParams struct {
	PersonID int32
}

// TrendingAllParams is parameters of trending-all operation.
type TrendingAllParams struct {
	TimeWindow TrendingAllTimeWindow
	// `ISO-639-1`-`ISO-3166-1` code.
	Language OptString
}

// TrendingMoviesParams is parameters of trending-movies operation.
type TrendingMoviesParams struct {
	TimeWindow TrendingMoviesTimeWindow
	// `ISO-639-1`-`ISO-3166-1` code.
	Language OptString
}

// TrendingPeopleParams is parameters of trending-people operation.
type TrendingPeopleParams struct {
	TimeWindow TrendingPeopleTimeWindow
	// `ISO-639-1`-`ISO-3166-1` code.
	Language OptString
}

// TrendingTvParams is parameters of trending-tv operation.
type TrendingTvParams struct {
	TimeWindow TrendingTvTimeWindow
	// `ISO-639-1`-`ISO-3166-1` code.
	Language OptString
}

// TvEpisodeAccountStatesParams is parameters of tv-episode-account-states operation.
type TvEpisodeAccountStatesParams struct {
	SeriesID       int32
	SessionID      OptString
	SeasonNumber   int32
	EpisodeNumber  int32
	GuestSessionID OptString
}

// TvEpisodeAddRatingParams is parameters of tv-episode-add-rating operation.
type TvEpisodeAddRatingParams struct {
	SeriesID       int32
	GuestSessionID OptString
	SessionID      OptString
	SeasonNumber   int32
	EpisodeNumber  int32
}

// TvEpisodeChangesByIDParams is parameters of tv-episode-changes-by-id operation.
type TvEpisodeChangesByIDParams struct {
	EpisodeID int32
}

// TvEpisodeCreditsParams is parameters of tv-episode-credits operation.
type TvEpisodeCreditsParams struct {
	SeriesID      int32
	SeasonNumber  int32
	Language      OptString
	EpisodeNumber int32
}

// TvEpisodeDeleteRatingParams is parameters of tv-episode-delete-rating operation.
type TvEpisodeDeleteRatingParams struct {
	SeriesID       int32
	GuestSessionID OptString
	SessionID      OptString
	SeasonNumber   int32
	EpisodeNumber  int32
}

// TvEpisodeDetailsParams is parameters of tv-episode-details operation.
type TvEpisodeDetailsParams struct {
	SeriesID      int32
	SeasonNumber  int32
	EpisodeNumber int32
	// Comma separated list of endpoints within this namespace, 20 items max.
	AppendToResponse OptString
	Language         OptString
}

// TvEpisodeExternalIdsParams is parameters of tv-episode-external-ids operation.
type TvEpisodeExternalIdsParams struct {
	SeriesID      int32
	SeasonNumber  int32
	EpisodeNumber string
}

// TvEpisodeGroupDetailsParams is parameters of tv-episode-group-details operation.
type TvEpisodeGroupDetailsParams struct {
	TvEpisodeGroupID string
}

// TvEpisodeImagesParams is parameters of tv-episode-images operation.
type TvEpisodeImagesParams struct {
	SeriesID int32
	// Specify a comma separated list of ISO-639-1 values to query, for example: `en,null`.
	IncludeImageLanguage OptString
	Language             OptString
	SeasonNumber         int32
	EpisodeNumber        int32
}

// TvEpisodeTranslationsParams is parameters of tv-episode-translations operation.
type TvEpisodeTranslationsParams struct {
	SeriesID      int32
	SeasonNumber  int32
	EpisodeNumber int32
}

// TvEpisodeVideosParams is parameters of tv-episode-videos operation.
type TvEpisodeVideosParams struct {
	SeriesID int32
	// Filter the list results by language, supports more than one value by using a comma.
	IncludeVideoLanguage OptString
	Language             OptString
	SeasonNumber         int32
	EpisodeNumber        int32
}

// TvSeasonAccountStatesParams is parameters of tv-season-account-states operation.
type TvSeasonAccountStatesParams struct {
	SeriesID       int32
	SessionID      OptString
	GuestSessionID OptString
	SeasonNumber   int32
}

// TvSeasonAggregateCreditsParams is parameters of tv-season-aggregate-credits operation.
type TvSeasonAggregateCreditsParams struct {
	SeriesID     int32
	Language     OptString
	SeasonNumber int32
}

// TvSeasonChangesByIDParams is parameters of tv-season-changes-by-id operation.
type TvSeasonChangesByIDParams struct {
	EndDate   OptString
	Page      OptInt32
	StartDate OptString
	SeasonID  int32
}

// TvSeasonCreditsParams is parameters of tv-season-credits operation.
type TvSeasonCreditsParams struct {
	SeriesID     int32
	SeasonNumber int32
	Language     OptString
}

// TvSeasonDetailsParams is parameters of tv-season-details operation.
type TvSeasonDetailsParams struct {
	SeriesID     int32
	SeasonNumber int32
	// Comma separated list of endpoints within this namespace, 20 items max.
	AppendToResponse OptString
	Language         OptString
}

// TvSeasonExternalIdsParams is parameters of tv-season-external-ids operation.
type TvSeasonExternalIdsParams struct {
	SeriesID     int32
	SeasonNumber int32
}

// TvSeasonImagesParams is parameters of tv-season-images operation.
type TvSeasonImagesParams struct {
	SeriesID int32
	// Specify a comma separated list of ISO-639-1 values to query, for example: `en,null`.
	IncludeImageLanguage OptString
	Language             OptString
	SeasonNumber         int32
}

// TvSeasonTranslationsParams is parameters of tv-season-translations operation.
type TvSeasonTranslationsParams struct {
	SeriesID     int32
	SeasonNumber int32
}

// TvSeasonVideosParams is parameters of tv-season-videos operation.
type TvSeasonVideosParams struct {
	SeriesID int32
	// Filter the list results by language, supports more than one value by using a comma.
	IncludeVideoLanguage OptString
	Language             OptString
	SeasonNumber         int32
}

// TvSeasonWatchProvidersParams is parameters of tv-season-watch-providers operation.
type TvSeasonWatchProvidersParams struct {
	SeriesID     int32
	Language     OptString
	SeasonNumber int32
}

// TvSeriesAccountStatesParams is parameters of tv-series-account-states operation.
type TvSeriesAccountStatesParams struct {
	SeriesID       int32
	SessionID      OptString
	GuestSessionID OptString
}

// TvSeriesAddRatingParams is parameters of tv-series-add-rating operation.
type TvSeriesAddRatingParams struct {
	SeriesID       int32
	GuestSessionID OptString
	SessionID      OptString
}

// TvSeriesAggregateCreditsParams is parameters of tv-series-aggregate-credits operation.
type TvSeriesAggregateCreditsParams struct {
	SeriesID int32
	Language OptString
}

// TvSeriesAiringTodayListParams is parameters of tv-series-airing-today-list operation.
type TvSeriesAiringTodayListParams struct {
	Language OptString
	Page     OptInt32
	Timezone OptString
}

// TvSeriesAlternativeTitlesParams is parameters of tv-series-alternative-titles operation.
type TvSeriesAlternativeTitlesParams struct {
	SeriesID int32
}

// TvSeriesChangesParams is parameters of tv-series-changes operation.
type TvSeriesChangesParams struct {
	SeriesID  int32
	EndDate   OptString
	Page      OptInt32
	StartDate OptString
}

// TvSeriesContentRatingsParams is parameters of tv-series-content-ratings operation.
type TvSeriesContentRatingsParams struct {
	SeriesID int32
}

// TvSeriesCreditsParams is parameters of tv-series-credits operation.
type TvSeriesCreditsParams struct {
	SeriesID int32
	Language OptString
}

// TvSeriesDeleteRatingParams is parameters of tv-series-delete-rating operation.
type TvSeriesDeleteRatingParams struct {
	SeriesID       int32
	GuestSessionID OptString
	SessionID      OptString
}

// TvSeriesDetailsParams is parameters of tv-series-details operation.
type TvSeriesDetailsParams struct {
	SeriesID int32
	// Comma separated list of endpoints within this namespace, 20 items max.
	AppendToResponse OptString
	Language         OptString
}

// TvSeriesEpisodeGroupsParams is parameters of tv-series-episode-groups operation.
type TvSeriesEpisodeGroupsParams struct {
	SeriesID int32
}

// TvSeriesExternalIdsParams is parameters of tv-series-external-ids operation.
type TvSeriesExternalIdsParams struct {
	SeriesID int32
}

// TvSeriesImagesParams is parameters of tv-series-images operation.
type TvSeriesImagesParams struct {
	SeriesID int32
	// Specify a comma separated list of ISO-639-1 values to query, for example: `en,null`.
	IncludeImageLanguage OptString
	Language             OptString
}

// TvSeriesKeywordsParams is parameters of tv-series-keywords operation.
type TvSeriesKeywordsParams struct {
	SeriesID int32
}

// TvSeriesOnTheAirListParams is parameters of tv-series-on-the-air-list operation.
type TvSeriesOnTheAirListParams struct {
	Language OptString
	Page     OptInt32
	Timezone OptString
}

// TvSeriesPopularListParams is parameters of tv-series-popular-list operation.
type TvSeriesPopularListParams struct {
	Language OptString
	Page     OptInt32
}

// TvSeriesRecommendationsParams is parameters of tv-series-recommendations operation.
type TvSeriesRecommendationsParams struct {
	SeriesID int32
	Language OptString
	Page     OptInt32
}

// TvSeriesReviewsParams is parameters of tv-series-reviews operation.
type TvSeriesReviewsParams struct {
	SeriesID int32
	Language OptString
	Page     OptInt32
}

// TvSeriesScreenedTheatricallyParams is parameters of tv-series-screened-theatrically operation.
type TvSeriesScreenedTheatricallyParams struct {
	SeriesID int32
}

// TvSeriesSimilarParams is parameters of tv-series-similar operation.
type TvSeriesSimilarParams struct {
	SeriesID string
	Language OptString
	Page     OptInt32
}

// TvSeriesTopRatedListParams is parameters of tv-series-top-rated-list operation.
type TvSeriesTopRatedListParams struct {
	Language OptString
	Page     OptInt32
}

// TvSeriesTranslationsParams is parameters of tv-series-translations operation.
type TvSeriesTranslationsParams struct {
	SeriesID int32
}

// TvSeriesVideosParams is parameters of tv-series-videos operation.
type TvSeriesVideosParams struct {
	SeriesID int32
	// Filter the list results by language, supports more than one value by using a comma.
	IncludeVideoLanguage OptString
	Language             OptString
}

// TvSeriesWatchProvidersParams is parameters of tv-series-watch-providers operation.
type TvSeriesWatchProvidersParams struct {
	SeriesID int32
}

// WatchProviderTvListParams is parameters of watch-provider-tv-list operation.
type WatchProviderTvListParams struct {
	Language    OptString
	WatchRegion OptString
}

// WatchProvidersAvailableRegionsParams is parameters of watch-providers-available-regions operation.
type WatchProvidersAvailableRegionsParams struct {
	Language OptString
}

// WatchProvidersMovieListParams is parameters of watch-providers-movie-list operation.
type WatchProvidersMovieListParams struct {
	Language    OptString
	WatchRegion OptString
}
